SoftUni-s-Team-Lead-AI-Social-Platform/AI-Social-Platform

AI-Social-Platform.Server/AI-Social-Platform.Server.csproj
ai-social-platform.client/.vite/deps_temp_a5692b0f/package.json

Мисля, че това е проблема на колегата с грешката

Project settings edit

---

AI-Social-Platform.Server/AI-Social-Platform.Server.csproj
AI-Social-Platform.Server/Program.cs
AI-Social-Platform.Services.Data/UserService.cs

Adding nuget package and default identity

Adding nuget package and default identity

---

AI-Social-Platform.FormModels/LoginResponse.cs
AI-Social-Platform.Server/Controllers/UserController.cs
AI-Social-Platform.Server/Program.cs
AI-Social-Platform.Services.Data/Interfaces/IUserService.cs
AI-Social-Platform.Services.Data/UserService.cs

Enhancements to the Login

---

AI-Social-Platform.Server/Controllers/PublicationController.cs
AI-Social-Platform.Server/Controllers/UserController.cs
AI-Social-Platform.Server/Program.cs
AI-Social-Platform.Services.Data/UserService.cs

Added signIn through the manager plus default
authentication scheme for the application.

Added signIn through the manager plus default authentication scheme

---

AI-Social-Platform.Extensions/ClaimsPrincipalExtensions.cs
AI-Social-Platform.Server/Controllers/MediaController.cs
AI-Social-Platform.Server/Controllers/UserController.cs

change name on method GetUserId to GetUserEmail because it's return user email

fix method name GetUserId to GetUserEmail

---

AI-Social-Platform.Common/ExceptionMessages.cs
AI-Social-Platform.Common/NotificationMessagesConstants.cs
AI-Social-Platform.Data/Configurations/PublicationEntityConfiguration.cs
AI-Social-Platform.Data/Migrations/20231126032732_updateDeleteBehaviorOnPublication.Designer.cs
AI-Social-Platform.Data/Migrations/20231126032732_updateDeleteBehaviorOnPublication.cs
AI-Social-Platform.Server/Controllers/MediaController.cs
AI-Social-Platform.Server/Controllers/PublicationController.cs
AI-Social-Platform.Server/Controllers/UserController.cs
AI-Social-Platform.Server/Program.cs
AI-Social-Platform.Services.Data.Models/PublicationDtos/CommentDto.cs
AI-Social-Platform.Services.Data.Models/PublicationDtos/CommentFormDto.cs
AI-Social-Platform.Services.Data.Models/PublicationDtos/PublicationDto.cs
AI-Social-Platform.Services.Data.Models/PublicationDtos/PublicationFormDto.cs
AI-Social-Platform.Services.Data/PublicationService.cs
AI-Social-Platform.sln
Ai-Social-Platform.Tests/Ai-Social-Platform.Tests.csproj
Ai-Social-Platform.Tests/DatabaseSeeder.cs
Ai-Social-Platform.Tests/GlobalUsings.cs
Ai-Social-Platform.Tests/PublicationServiceTest.cs

Optimized the publication service
Created tests for the service
Mock the dbContext
Mock the httpcontext
Better restful controller returns
i changed the name of GetUserEmail() to the correct name because after the latest merge it wasnt able to build

Publication comment tests

---

AI-Social-Platform.Server/Controllers/MediaController.cs
AI-Social-Platform.Services.Data/Interfaces/IMediaService.cs
AI-Social-Platform.Services.Data/MediaService.cs

change upload method can select many files instead of one, generate get method by media id

fix media controller

---

ai-social-platform.client/src/components/Register/Register.jsx
ai-social-platform.client/src/components/Register/Register.module.css
ai-social-platform.client/src/components/Register/registerValidation.js
ai-social-platform.client/src/core/environments/costants.js

Add formik to register component, get form values, add form validation, create object with keys for register form, add css for error messages.

Register component functionality

---

AI-Social-Platform.Common/NotificationMessagesConstants.cs
AI-Social-Platform.FormModels/RegisterFormModel.cs
AI-Social-Platform.Server/AI-Social-Platform.Server.csproj
AI-Social-Platform.Server/Controllers/UserController.cs
AI-Social-Platform.Server/Program.cs
AI-Social-Platform.Services.Data/Interfaces/IUserService.cs
AI-Social-Platform.Services.Data/UserService.cs

If login fail returning 400
If user email already registered returns 400
fix wrong namespace on a form model

User controller restful + certificate add

---

AI-Social-Platform.Server/Controllers/TopicController.cs
AI-Social-Platform.Services.Data/Interfaces/ITopicService.cs
AI-Social-Platform.Services.Data/TopicService.cs
Ai-Social-Platform.Tests/PublicationServiceTest.cs

add unfollow topic, get followed topics by user id and get publicatins by topic id methods

topicController methods

---

AI-Social-Platform.Server/Controllers/SocialFeatureController.cs
AI-Social-Platform.Services.Data.Models/SocialFeature/SearchTopicDto.cs
AI-Social-Platform.Services.Data/BaseSocialService.cs
AI-Social-Platform.Services.Data/Interfaces/IBaseSocialService.cs
AI-Social-Platform.Services.Data/MappingProfiles/MapperProfiles.cs

The search functionality works for users, publications and topics
The search type must be one of the three "user", "publication" or "topic"
User is searched by first name or last name,
Publication is searched by Content,
Topic by title

Search feature

---

AI-Social-Platform.FormModels/LoginResponse.cs
AI-Social-Platform.Server/Controllers/UserController.cs
AI-Social-Platform.Services.Data.Models/UserDto/UserDetailsDto.cs
AI-Social-Platform.Services.Data.Models/UserDto/UserDto.cs
AI-Social-Platform.Services.Data/BaseSocialService.cs
AI-Social-Platform.Services.Data/UserService.cs

Fix GetUserDetails to return profil picture and cover photo with url and login response to return profil picture with url

Fix user profil and cover photo

---

AI-Social-Platform.Server/Controllers/MediaController.cs
AI-Social-Platform.Server/Controllers/PublicationController.cs
AI-Social-Platform.Server/Controllers/SocialFeatureController.cs
AI-Social-Platform.Server/Controllers/TopicController.cs
AI-Social-Platform.Server/Controllers/UserController.cs
AI-Social-Platform.Services.Data.Models/PublicationDtos/IndexPublicationDto.cs
AI-Social-Platform.Services.Data.Models/PublicationDtos/PublicationDto.cs
AI-Social-Platform.Services.Data.Models/SocialFeature/IndexCommentDto.cs
AI-Social-Platform.Services.Data/BaseSocialService.cs
AI-Social-Platform.Services.Data/Interfaces/IPublicationService.cs
AI-Social-Platform.Services.Data/MappingProfiles/MapperProfiles.cs
AI-Social-Platform.Services.Data/PublicationService.cs
Ai-Social-Platform.Tests/DatabaseSeeder.cs
Ai-Social-Platform.Tests/PublicationServiceTest.cs

including 2 latest comments in get/publications
basic filtering implemented in get/publications
updating get/publication/id
[returning the publication on Create] - request from FE
[every endpoint and error returning json instead of string] - request from FE

Filter publications feature

---

AI-Social-Platform.FormModels/UpdateUserFormModel.cs
AI-Social-Platform.FormModels/UserFormModel.cs
AI-Social-Platform.Server/Controllers/UserController.cs
AI-Social-Platform.Services.Data/UserService.cs

UpdateUser Repair

---

AI-Social-Platform.FormModels/UserFormModel.cs
AI-Social-Platform.Services.Data/UserService.cs

Edit User Update

---

AI-Social-Platform.Server/Controllers/SocialFeatureController.cs
AI-Social-Platform.Services.Data.Models/PublicationDtos/PublicationDto.cs
AI-Social-Platform.Services.Data.Models/UserDto/UserDetailsDto.cs
AI-Social-Platform.Services.Data/BaseSocialService.cs
AI-Social-Platform.Services.Data/Interfaces/IBaseSocialService.cs
AI-Social-Platform.Services.Data/MappingProfiles/MapperProfiles.cs
AI-Social-Platform.Services.Data/PublicationService.cs

request from FE
Each publication has property bool "IsLiked" from the current user
Update comment returns the comment

Edit comment change

---

AI-Social-Platform.Common/ExceptionMessages.cs
AI-Social-Platform.Common/NotificationMessagesConstants.cs
AI-Social-Platform.Server/Controllers/SocialFeatureController.cs
AI-Social-Platform.Services.Data.Models/SocialFeature/NotificationDto.cs
AI-Social-Platform.Services.Data/BaseSocialService.cs
AI-Social-Platform.Services.Data/Interfaces/IBaseSocialService.cs

[Return like on create]
[Notification endpoint for count of the unread ones]
[Notification endpoint for set to true on isRead]

Like change &&  notification helper endpoints

---

AI-Social-Platform.Data.Models/ApplicationUser.cs
AI-Social-Platform.Data.Models/Friendship.cs
AI-Social-Platform.Data/ASPDbContext.cs
AI-Social-Platform.Data/Configurations/ApplicationUserEntityConfiguration.cs
AI-Social-Platform.Data/Migrations/20240120124923_AddSelfReferenceManyToManyTableUsersFriends.Designer.cs
AI-Social-Platform.Data/Migrations/20240120124923_AddSelfReferenceManyToManyTableUsersFriends.cs
AI-Social-Platform.Data/Migrations/20240120175232_removeFriendsCollectionSelfReference.Designer.cs
AI-Social-Platform.Data/Migrations/20240120175232_removeFriendsCollectionSelfReference.cs
AI-Social-Platform.Server/Controllers/PublicationController.cs
AI-Social-Platform.Server/Controllers/UserController.cs
AI-Social-Platform.Services.Data/BaseSocialService.cs
AI-Social-Platform.Services.Data/Interfaces/IPublicationService.cs
AI-Social-Platform.Services.Data/Interfaces/IUserService.cs
AI-Social-Platform.Services.Data/PublicationService.cs
AI-Social-Platform.Services.Data/UserService.cs

The friendlist bug is fixed && get publications query optimized 
Two new migrations - the bug was related to the self reference collection(Friends)
I added a many to many mapping table to fix that (Friendships)

Fix user friendlist

---

AI-Social-Platform.Data.Models/Media.cs
AI-Social-Platform.Data/Migrations/20240128101912_removeSoftDeleteMediaProperty.Designer.cs
AI-Social-Platform.Data/Migrations/20240128101912_removeSoftDeleteMediaProperty.cs
AI-Social-Platform.Services.Data/MediaService.cs

after merge this needs update-database

media-delete-fix

---

AI-Social-Platform.Server/Controllers/OpenAIController.cs

Translate from * language to * language ai endpoint

Feature translate ai

---

AI-Social-Platform.Services.Data/BaseSocialService.cs
AI-Social-Platform.Services.Data/PublicationService.cs
AI-Social-Platform.Services.Data/UserService.cs

logged in user included in the dashboard
Notification bug fixes

Publications user feed

---

AI-Social-Platform.FormModels/LoginResponse.cs
AI-Social-Platform.Server/Controllers/UserController.cs
AI-Social-Platform.Services.Data/Interfaces/IUserService.cs
AI-Social-Platform.Services.Data/UserService.cs

Anton 30 01

---

AI-Social-Platform.Server/Controllers/UserController.cs
AI-Social-Platform.Services.Data/Interfaces/IUserService.cs
AI-Social-Platform.Services.Data/UserService.cs

Added method to check if users are friends

UsersAreFriends

---

AI-Social-Platform.Services.Data/BaseSocialService.cs
AI-Social-Platform.Services.Data/MappingProfiles/MapperProfiles.cs
AI-Social-Platform.Services.Data/PublicationService.cs

user.profilePictureUrl now is working as expected in publications, comments, likes, searches
We talked with Georgi, this one need some syntax changes from FE
After his PR this one will work too

User profilePictureUrl fix

---

AI-Social-Platform.Server/.config/dotnet-tools.json
AI-Social-Platform.Server/Program.cs
AI-Social-Platform.Server/Properties/ServiceDependencies/AI-Social-Platform - Web Deploy/mssql1.arm.json
AI-Social-Platform.Server/Properties/ServiceDependencies/AI-Social-Platform - Web Deploy/profile.arm.json
AI-Social-Platform.Server/Properties/serviceDependencies.AI-Social-Platform - Web Deploy.json
AI-Social-Platform.Server/Properties/serviceDependencies.json
AI-Social-Platform.Server/Properties/serviceDependencies.local.json
ai-social-platform.client/src/core/environments/costants.js

AddFix loading of configuration files, so connection string is read with proper priority. Add CORS policy for production FE url. Add Publishing profile generated settings.

Add Azure deploy fixes and settings
